# Generated by Django 4.2.7 on 2023-11-12 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
