# Generated by Django 4.2.7 on 2023-11-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_rename_doctorname_doctor_name"),
        ("patients", "0001_initial"),
        ("treatments", "0002_treatment_createdat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="doctorId",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="patientId",
        ),
        migrations.AddField(
            model_name="treatment",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
    ]
