# Generated by Django 4.2.7 on 2023-11-11 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="doctorName",
            new_name="name",
        ),
    ]
